# fly.toml app configuration file generated for africa-mix-bot-bitter-dream-8152 on 2026-02-17T18:46:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'africa-mix-bot-bitter-dream-8152'
primary_region = 'fra'

[build]
  builder = 'paketobuildpacks/builder:base'

[[vm]]
  memory = '2gb'
  cpus = 1
  memory_mb = 2048
